sensor:
  - platform: template
    sensors:
      flightradar24_current_in_area:
        friendly_name: "Flights in Area"
        value_template: "4"
        attribute_templates:
          flights: >
            {% set flights = [
              {
                "flight_number": "BA123",
                "callsign": "SPEEDBIRD123",
                "airline": "British Airways",
                "airline_short": "BA",
                "airline_iata": "BA",
                "airline_icao": "BAW",
                "aircraft_model": "A320",
                "aircraft_code": "A320",
                "aircraft_registration": "G-EUUA",
                "airport_origin_city": "London",
                "airport_origin_name": "London Heathrow Airport",
                "airport_origin_code_iata": "LHR",
                "airport_origin_code_icao": "EGLL",
                "airport_origin_country_code": "GB",
                "airport_origin_country_name": "United Kingdom",
                "airport_destination_city": "Paris",
                "airport_destination_name": "Paris Charles de Gaulle Airport",
                "airport_destination_code_iata": "CDG",
                "airport_destination_code_icao": "LFPG",
                "airport_destination_country_code": "FR",
                "airport_destination_country_name": "France",
                "time_scheduled_departure": "2024-04-19T10:00:00Z",
                "time_scheduled_arrival": "2024-04-19T12:00:00Z",
                "altitude": 35000,
                "ground_speed": 450,
                "vertical_speed": 0,
                "tracked_type": "live",
                "latitude": 50.1109,
                "longitude": 1.1848,
                "heading": 135
              },
              {
                "flight_number": "AF456",
                "callsign": "AIRFRANS456",
                "airline": "Air France",
                "airline_short": "AF",
                "airline_iata": "AF",
                "airline_icao": "AFR",
                "aircraft_model": "B777",
                "aircraft_code": "B777",
                "aircraft_registration": "F-GSQD",
                "airport_origin_city": "Paris",
                "airport_origin_name": "Paris Charles de Gaulle Airport",
                "airport_origin_code_iata": "CDG",
                "airport_origin_code_icao": "LFPG",
                "airport_origin_country_code": "FR",
                "airport_origin_country_name": "France",
                "airport_destination_city": "New York",
                "airport_destination_name": "John F. Kennedy International Airport",
                "airport_destination_code_iata": "JFK",
                "airport_destination_code_icao": "KJFK",
                "airport_destination_country_code": "US",
                "airport_destination_country_name": "United States",
                "time_scheduled_departure": "2024-04-19T14:00:00Z",
                "time_scheduled_arrival": "2024-04-19T20:00:00Z",
                "altitude": 38000,
                "ground_speed": 500,
                "vertical_speed": 0,
                "tracked_type": "live",
                "latitude": 48.8566,
                "longitude": 2.3522,
                "heading": 285
              },
              {
                "flight_number": "DL789",
                "callsign": "DELTA789",
                "airline": "Delta Air Lines",
                "airline_short": "DL",
                "airline_iata": "DL",
                "airline_icao": "DAL",
                "aircraft_model": "B737",
                "aircraft_code": "B737",
                "aircraft_registration": "N123DL",
                "tracked_type": "historical",
                "latitude": 33.7490,
                "longitude": -84.3880,
                "heading": 45
              },
              {
                "flight_number": "UA1234",
                "callsign": "UNITED1234",
                "airline": "United Airlines",
                "airline_short": "UA",
                "airline_iata": "UA",
                "airline_icao": "UAL",
                "aircraft_model": "B787",
                "aircraft_code": "B787",
                "aircraft_registration": "N12345",
                "airport_origin_city": "Chicago",
                "airport_origin_name": "O'Hare International Airport",
                "airport_origin_code_iata": "ORD",
                "airport_origin_code_icao": "KORD",
                "airport_destination_city": "Tokyo",
                "airport_destination_name": "Narita International Airport",
                "airport_destination_code_iata": "NRT",
                "airport_destination_code_icao": "RJAA",
                "airport_destination_country_code": "JP",
                "airport_destination_country_name": "Japan",
                "time_scheduled_departure": "2024-04-19T15:30:00Z",
                "time_scheduled_arrival": "2024-04-20T08:45:00Z",
                "altitude": 36000,
                "ground_speed": 480,
                "vertical_speed": 0,
                "tracked_type": "live",
                "latitude": 41.8781,
                "longitude": -87.6298,
                "heading": 315
              }
            ] %}
            {{ flights | to_json }} 